name: Kubernetes CI for ArgoCd using GitHub Actions
on:
  push:
   branches:
     - main

jobs:
  build_image:
    name: Build the docker image and scan with trivy
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha.outputs.SHORT_SHA }}
    steps:
      - name: Checking out the code
        uses: actions/checkout@v4
      - name: Setup short SHA for later use
        id: sha
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: biswarup007/python-app:${{ steps.sha.outputs.SHORT_SHA }}
      - name: Save image to tar
        run: |
          docker save biswarup007/python-app:${{ steps.sha.outputs.SHORT_SHA }} \
            -o python-app.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
            name: python-app-image
            path: python-app.tar
  scan_image:
    needs: build_image
    runs-on: ubuntu-latest
    outputs:
      critical: ${{ steps.trivy_metrics.outputs.critical }}
      high: ${{ steps.trivy_metrics.outputs.high }}
      medium: ${{ steps.trivy_metrics.outputs.medium }}
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app-image
      - name: Load docker image
        run: |
          docker load -i python-app.tar
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: biswarup007/python-app:${{ needs.build_image.outputs.short_sha }}
          severity: MEDIUM,HIGH,CRITICAL
          exit-code: 0
          format: json
          output: trivy-report.json
      - name: Parse Trivy metrics
        id: trivy_metrics
        run: |
          CRITICAL=$(jq '[.Results[].Vulnerabilities[] | select(.Severity=="CRITICAL")] | length' trivy-report.json)
          HIGH=$(jq '[.Results[].Vulnerabilities[] | select(.Severity=="HIGH")] | length' trivy-report.json)
          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT
          echo "medium=$MEDIUM" >> $GITHUB_OUTPUT

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
  sending_slack_notitification:
    name: Sending notification
    needs: scan_image
    uses: ./.github/workflows/reusable-slack-notification.yml
    if: always()
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      payload: |
        {
        text : "GitHub Actions Notification: Trivy scan results",
        blocks:
          - type: section
              text:
                type: mrkdwn
                  text: ":rocket: *GitHub Actions Notification*"
          - type: section
            fields:
              - type: mrkdwn
                text: "*Repository:*\n${{ github.repository }}"
              - type: mrkdwn
                text: "*Branch:*\n${{ github.ref_name }}"
              - type: mrkdwn
                text: "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|View Commit>"
          - type: section
            fields:
              - type: mrkdwn
                text: "*CRITICAL:*\n${{ needs.scan_image.outputs.critical }}"
              - type: mrkdwn
                text: "*HIGH:*\n${{ needs.scan_image.outputs.high }}"
              - type: mrkdwn
                text: "*MEDIUM:*\n${{ needs.scan_image.outputs.medium }}"
          }
  pushing_image_to_docker_hub:
    name: Pushing the image to docker hub
    needs: ['sending_slack_notitification', 'build_image']
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app-image
      - name: Load docker image
        run: |
          docker load -i python-app.tar
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Push docker image
        run: docker push biswarup007/python-app:${{ needs.build_image.outputs.short_sha }}
  changing_the_kubernetes_deployment_and_commit:
    name: Changing the kubernetes deployment file
    needs: pushing_image_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v4
      - name: Installing yq
        uses: mikefarah/yq@v4.44.3
      - name: Update deployment.yml file
        run: |
          # Creating the SHA KEY
          SHORT_SHA_KEY=${GITHUB_SHA::10}
          # Update the image tag in the kubernetes deployment yaml file
          yq -i '.spec.template.spec.containers[0].image = "biswarup007/python-app:'"$SHORT_SHA_KEY"'"' ./k8s/deployment.yml
      - name: Commiting the changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@noreply"
          git commit -am "updated the deployment.yml file by GitHub Actions" || echo "Already commited the changes"
          git push origin main      
  success_notify:
    uses: ./.github/workflows/reusable-slack-notification.yml
    needs: ['build_image', 'scan_image','sending_slack_notitification', 'pushing_image_to_docker_hub', 'changing_the_kubernetes_deployment_and_commit']
    if: always() && !failure()
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      payload: |
        {
        "text": ":white_check_mark: *CI Pipeline Successful!* 🎉\n\n*Repository:* `${{ github.repository }}`\n*Branch:* `${{ github.ref_name }}`\n*Commit:* `<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>`\n*Triggered by:* `${{ github.actor }}`\n\n:docker: Docker image built, scanned & pushed\n:kubernetes: Deployment YAML updated\n\n:rocket: *Ready for ArgoCD sync!*"
        }
  failure_notify:
    uses: ./.github/workflows/reusable-slack-notification.yml
    needs: ['build_image', 'scan_image','sending_slack_notitification', 'pushing_image_to_docker_hub', 'changing_the_kubernetes_deployment_and_commit']
    if: failure()
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      payload: |
        {
        "text": ":rotating_light: *CI Pipeline FAILED!* :x:\n\n*Repository:* `${{ github.repository }}`\n*Branch:* `${{ github.ref_name }}`\n*Commit:* `<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>`\n*Triggered by:* `${{ github.actor }}`\n\n:warning: One or more steps failed during the pipeline execution.\n\n:mag: *Action Required*\n• Check the GitHub Actions logs\n• Fix the issue and re-run the pipeline\n\n:link: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Logs>"
        }